### ISSUE TITLE
Realizar Demo Sprint 3

### ISSUE THREAD

**Issue by pgmarc** [ISPP-23-24-Grupo-3/MuscleMate-Documentation#115]
Hacer la demo cuando la **Aplicación esté completa y funcional**

- [ ] Introducción de la demo
- [ ] Dejo claro en la demo, cuando soy un cliente de gimnasio o un propietario (Utiliza una icono u otra metafora visual)
- [ ] En la demo se muestran los usuarios que aparecen en el anuncio
- [ ] Incluir Changelog (Que funcionalidades se han añadido desde la demo del Sprint 2) en la demo
- [ ] Mostrar Incremento de la demo del Sprint 3
- [ ] Se usan datos realistas
- [ ] Se hace zoom en las características
- [ ] Doblar la demo
- [ ] No muestro el proceso de login y registro

Crear una diapositiva con tu nombre (mas tarde se borrará) con la información sintetizada, cosas a tener en cuenta, no seas escueto, cuenta lo esencial, importante, no te quedes a bajo nivel, una diapositiva o las diapositivas que tengas que hacer currada, letras medianamente grandes que se vean desde atrás, cuida el formato de la ppt y sobre todo, escucha el audio o la transcripción del final de la clase y mas si no estuviste en la clase mientras lo decia. Puedes preguntar a otros grupos como Ocial o coabify como han hecho ellos esa parte de la documentación y las diapositivas.

https://www.canva.com/design/DAGBd6p4uSI/-1jXSGV-uUwSYKghAEsRCw/edit?utm_content=DAGBd6p4uSI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Plásmalo aqui, a ser posible crea una copia para ti y despues solo se corta y pega la diapositiva en concreto.

**Comment by manortgar** [comment]
![image](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/assets/80253414/47d93cbd-8f40-4c1b-810f-0c2e7d43ac99)
![image](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/assets/80253414/a9c20793-2216-4d7d-8f72-489c3b5d3b59)
![image](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/assets/80253414/23e4ba34-2383-49db-bdd6-bd5f6f7c90a8)
