### ISSUE TITLE
Actualizar Estructura del equipo

### ISSUE THREAD

**Issue by pgmarc** [ISPP-23-24-Grupo-3/MuscleMate-Documentation#136]
- [x] Redactar la estructura del equipo en un documento (Revisa si hay uno creado previamente)
- [x] Asignar un community manager o decir que está subcontratado
- [x] Asignar un GDPR compliance officer
- [x] Volcar la información en la presentación
- [x] El contenido se ve desde el fondo de la clase

**Comment by lemonada02** [comment]
https://lucid.app/lucidchart/e33b64ee-8ef3-424b-8fb2-f52f79219a16/edit?viewport_loc=-62%2C209%2C2020%2C938%2C0_0&invitationId=inv_22f515b8-4ff6-45af-8609-32a4e40ba6ce
