### ISSUE TITLE
Pilotaje Grupo 9 Semana 9

### ISSUE THREAD

**Issue by angmunpri** [ISPP-23-24-Grupo-3/MuscleMate-Documentation#140]
Realizar el pilotaje del grupo 9 respecto al despliegue entregado 

Este es el formulario a rellenar: 
[Feedback 20-04-2024.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15052376/Feedback.20-04-2024.xlsx)

Se recuerda que al seguir los pasos detallados en el formulario no solo se debe añadir los errores sino tambien detallar aspectos que gusten de la aplicación.

Para probar el despliegue se tiene el siguiente enlace: https://cuidame-sprint3.ey.r.appspot.com/

Comentar en esta issue el formulario relleno con el nombre del que hace el pilotaje

**1 PUNTO DE HISTORIA POR PERSONA QUE REALICE EL PILOTAJE**

**Comment by luisgp9** [comment]
[Feedback.20-04-2024-LUIS-GARCIA-PARRAS.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15052560/Feedback.20-04-2024-LUIS-GARCIA-PARRAS.xlsx)
LUIS GARCIA PARRAS

**Comment by agudevbon** [comment]
[Feedback.20-04-2024-Agustín Devós.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15052689/Feedback.20-04-2024-Agustin.Devos.xlsx)

**Comment by manvazmar3** [comment]
Feedback Manuel Vázquez Martín 
[Feedback.20-04-2024-Manuel-Vazquez-Martin.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15052691/Feedback.20-04-2024-Manuel-Vazquez-Martin.xlsx)

**Comment by lemonada02** [comment]
[jorromlim-Feedback.20-04-2024J.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15052708/jorromlim-Feedback.20-04-2024J.xlsx)

**Comment by AMC112002** [comment]
[Feedback.20-04-2024. Alejandro Mateo Capilla.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15055644/Feedback.20-04-2024.Alejandro.Mateo.Capilla.xlsx)

**Comment by Leonidas6000** [comment]
[Feedback.20-04-2024-David-Dana-Cabello.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15061901/Feedback.20-04-2024-David-Dana-Cabello.xlsx)

**Comment by juanjesussevi** [comment]
[Feedback.JuanJesusMartínHernández-22-04-2024.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15062115/Feedback.JuanJesusMartinHernandez-22-04-2024.xlsx)
Juan Jesús Martín Hernández
