### ISSUE TITLE
Buscar información del mercado del mundo fitness (Anuncio de inversores)

### ISSUE THREAD

**Issue by pgmarc** [ISPP-23-24-Grupo-3/MuscleMate-Documentation#224]
Buscar información de los segmentos del mercado de los gimnasios (cifras, porcentajes).

Dejar en la lista de abajo los links con los datos

Links interesantes:
- [Gym industry](https://runrepeat.com/gym-industry-statistics)
- [Exercise](https://www.exercise.com/grow/gym-membership-statistics/#top-gym-membership-statistics)
- [Fitness Industry Statistics 2021-2028](https://runrepeat.com/fitness-industry)

**Comment by davidzarandieta** [comment]
- Según el informe del European Health & Fitness Market Report 2021, España es uno de los mercados más grandes de Europa en el sector de fitness. En 2020, el mercado español contaba con aproximadamente 4.3 millones de miembros de gimnasios .
- La mayoría de los miembros de gimnasios en España se concentran en las ciudades más grandes como Madrid, Barcelona y Sevilla. El perfil demográfico incluye una mayor participación de jóvenes adultos (18-35 años), aunque también hay un crecimiento en la población mayor de 55 años .
- En 2023, aproximadamente el 16.5% de la población en España asistió a un gimnasio.
- A día de hoy, en España hay aproximadamente 4,561 gimnasios operativos. De los cuales el 70% son gimnasios independientes que no pertenecen a ninguna cadena, significa que hay 3193 gimnasios independientes que son nuestro gimnasio objetivo. Aspiramos llegar a un 7%  (+300) de los gimnasios en España.
