### ISSUE TITLE
Pilotaje Grupo 9

### ISSUE THREAD

**Issue by angmunpri** [ISPP-23-24-Grupo-3/MuscleMate-Documentation#232]
* Url del Despliegue: https://cuidame-sprint3.ey.r.appspot.com/

* Formulario del Despliegue: 
[Feedback 12-05-2024.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15286726/Feedback.12-05-2024.xlsx)

* Rellenar el feedback comprobando todo bien, buscando fallos en la aplicación. Si se encuentran fallos no detectados por nosotros nos penaliza.

**Comment by luisgp9** [comment]
FEEDBACK LUIS GARCIA PARRAS
[Feedback.12-05-2024-LUIS GARCIA PARRAS.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15292637/Feedback.12-05-2024-LUIS.GARCIA.PARRAS.xlsx)

**Comment by manvazmar3** [comment]
FEEDBACK MANUEL VAZQUEZ MARTIN
[Feedback.12-05-2024-Manuel-Vazquez-Martin.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15294410/Feedback.12-05-2024-Manuel-Vazquez-Martin.xlsx)

**Comment by AMC112002** [comment]
[Uploading Feedback.12-05-2024. Alejandro Mateo Capilla.xlsx…]()

**Comment by juanjesussevi** [comment]
JUAN JESUS MARTIN HERNANDEZ
[Feedback.Juan Jesus Martin.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15296106/Feedback.Juan.Jesus.Martin.xlsx)

**Comment by angmunpri** [comment]
[Feedback.12-05-2024AngelMuñoz.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15296630/Feedback.12-05-2024AngelMunoz.xlsx)

**Comment by Leonidas6000** [comment]
[Feedback.12-05-2024 David Dana Cabello.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15298805/Feedback.12-05-2024.David.Dana.Cabello.xlsx)

**Comment by agudevos** [comment]
[Feedback.12-05-2024-Agustin-Devos-Bono.xlsx](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/files/15313121/Feedback.12-05-2024-Agustin-Devos-Bono.xlsx)

**Comment by pgmarc** [comment]
**Crear cuenta como cuidador**:
Dado un usuario ya creado:
![image](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/assets/72971636/96480f78-5855-4041-9677-211b6a201a58)

Si quiero registrar un nuevo usuario con el mismo `username` me dice lo siguiente:
Formación requerida
![registro-cuidador-experiencia-requerida](https://github.com/ISPP-23-24-Grupo-3/MuscleMate-Documentation/assets/72971636/73637dcc-7455-422d-8fea-721e16987832)
