### ISSUE TITLE
Actualizar/Crear AI-usage

### ISSUE THREAD

**Issue by pgmarc** [ISPP-23-24-Grupo-3/MuscleMate-Documentation#37]
# Formato
El documento deberá estar recogido en `Docusaurus` en formato `.md` o `.mdx`.
Debes respetar la portada, y el formato de documento. El formato está recogido en el archivo `FORMATO.md`.

# Descripcion
- Report detailing the AI-usage (AI-usage.md).
- Lecciones aprendidas usando la IA.
- Estimación de horas que quitar utilizar una IA en las diferentes tareas.
- Incluir contenido erróneo o de poca fiabilidad que ha generado la IA (alucinaciones de la IA lo llama Antonio).

# Incidencias
Si hiciste un documento que subiste a drive y no lo encuentras en el `Docusaurus` ponte en contacto con @manortgar.

**Comment by manvazmar3** [comment]
Documento realizado en:
https://docs.google.com/document/d/17GmTodNHWw5Pmp3wnWBBm3HAyqKsma45/edit
