### ISSUE TITLE
Actualizar/Crear Pilot Users Commitment Agreement or Agreements

### ISSUE THREAD

**Issue by pgmarc** [ISPP-23-24-Grupo-3/MuscleMate-Documentation#38]
# Formato
El documento deberá estar recogido en `Docusaurus` en formato `.md` o `.mdx`.
Debes respetar la portada, y el formato de documento. El formato está recogido en el archivo `FORMATO.md`.

# Descripcion
Pilot Users Commitment Agreement or Agreements (at least considering version, status, etc.)(pilotUsersCommitmentAgreement.md or several of them).

# Incidencias
Si hiciste un documento que subiste a drive y no lo encuentras en el `Docusaurus` ponte en contacto con @manortgar.

**Comment by Leonidas6000** [comment]
Angel elaboro el agreement de los usuarios del grupo 9 y manuel el de los usuarios anonimos.
