### ISSUE TITLE
Actualizar/Crear Docuemnto Problemas, Soluciones, Metricas

### ISSUE THREAD

**Issue by pgmarc** [ISPP-23-24-Grupo-3/MuscleMate-Documentation#87]
Problemas, Objetivo, Soluciones, Metricas (En las pidoras esto es el modelo GQA):
- [x] Vienen de un riesgos?,
- [x] Que se ha hecho para intentar solucionarlo?
- [x] Como se esta midiendo la efectividad de la solución?
- [x] Se ha solucionado realmente el problema?
- [x] Estado del problema si no se ha solucionado
- [x] Quitar los problemas de la parte de la retrospectiva (presentacion)
- [x] Seguir con la tabla y sintetizar el texto (presentacion):

Crear una diapositiva con tu nombre (mas tarde se borrará) con la información sintetizada, cosas a tener en cuenta, no seas escueto, cuenta lo esencial, importante, no te quedes a bajo nivel, una diapositiva o las diapositivas que tengas que hacer currada, letras medianamente grandes que se vean desde atrás, cuida el formato de la ppt y sobre todo, escucha el audio o la transcripción del final de la clase y mas si no estuviste en la clase mientras lo decia. Puedes preguntar a otros grupos como Ocial o coabify como han hecho ellos esa parte de la documentación y las diapositivas.

https://www.canva.com/design/DAGBd6p4uSI/-1jXSGV-uUwSYKghAEsRCw/edit?utm_content=DAGBd6p4uSI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Plásmalo aqui, a ser posible crea una copia para ti y despues solo se corta y pega la diapositiva en concreto.

**Comment by luisgp9** [comment]
Issue terminada por ahora, a falta de ver como evolucionan las issues de código para documentar un problema,
he creado una diapo de como mostrar la metodologia que seguimos para los problemas encontrados para que asi entiendan el proceso
las dos siguientes diapos muestran los problemas de la semana 9 y la anterior la 8

DIAPOS 55 56 Y 57

https://www.canva.com/design/DAGBd6p4uSI/-1jXSGV-uUwSYKghAEsRCw/edit?utm_content=DAGBd6p4uSI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
