### ISSUE TITLE
Actualizar Planificación Sprint 3

### ISSUE THREAD

**Issue by pgmarc** [ISPP-23-24-Grupo-3/MuscleMate-Documentation#91]
# Requisitos de cumplimiento
- [x] Sacar Screenshoot de ISSUES de Github Sprint 3 y posibles ISSUES de mejoras futuras
- [x] Incluir Tareas de Mejora del Sprint 3 (Ultimas mejoras de UX, Ultimos retoques, funcionalidad opcionales...)
- [x] Redactar si ha habido Replanificación
- [x] Realizar Pseudo Diagrama Gant con la planificación plasmada
- [x] Volcar información en la presentación
- [x] La información redactada en el documento es coherente con el contenido de la presentación
- [x] El contenido de la diapositiva se ve desde el fondo de la clase

Crear una diapositiva con tu nombre (mas tarde se borrará) con la información sintetizada, cosas a tener en cuenta, no seas escueto, cuenta lo esencial, importante, no te quedes a bajo nivel, una diapositiva o las diapositivas que tengas que hacer currada, letras medianamente grandes que se vean desde atrás, cuida el formato de la ppt y sobre todo, escucha el audio o la transcripción del final de la clase y mas si no estuviste en la clase mientras lo decia. Puedes preguntar a otros grupos como Ocial o coabify como han hecho ellos esa parte de la documentación y las diapositivas.

https://www.canva.com/design/DAGBd6p4uSI/-1jXSGV-uUwSYKghAEsRCw/edit?utm_content=DAGBd6p4uSI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Plásmalo aqui, a ser posible crea una copia para ti y despues solo se corta y pega la diapositiva en concreto.

**Comment by lemonada02** [comment]
https://app.asana.com/0/1207131881257303/1207131883043449
